import type { Checkpoint } from "./CheckpointTypes";
import type { AIProviderType } from "../ai";

export class CheckpointFilter {
  /**
   * Returns a new array containing only checkpoints created within the specified date range.
   */
  static filterByDate(
    checkpoints: Checkpoint[],
    options: { from?: number; to?: number },
  ): Checkpoint[] {
    return checkpoints.filter((cp) => {
      if (options.from !== undefined && cp.createdAt < options.from)
        return false;
      if (options.to !== undefined && cp.createdAt > options.to) return false;
      return true;
    });
  }

  /**
   * Returns a new array containing only checkpoints generated by a specific AI Provider.
   */
  static filterByProvider(
    checkpoints: Checkpoint[],
    provider: AIProviderType,
  ): Checkpoint[] {
    return checkpoints.filter((cp) => cp.summary.provider === provider);
  }

  /**
   * Returns a new array of checkpoints sorted chronologically.
   */
  static sortByCreatedAt(
    checkpoints: Checkpoint[],
    direction: "asc" | "desc",
  ): Checkpoint[] {
    // Slice creates a shallow copy to preserve immutability of the original array
    return checkpoints.slice().sort((a, b) => {
      return direction === "asc"
        ? a.createdAt - b.createdAt
        : b.createdAt - a.createdAt;
    });
  }

  /**
   * Returns a new array of checkpoints sorted by the volume of conversation messages.
   */
  static sortByConversationLength(
    checkpoints: Checkpoint[],
    direction: "asc" | "desc",
  ): Checkpoint[] {
    return checkpoints.slice().sort((a, b) => {
      const aLen = a.conversation.messageCount;
      const bLen = b.conversation.messageCount;
      return direction === "asc" ? aLen - bLen : bLen - aLen;
    });
  }
}
